# Generated by Django 5.2.6 on 2025-12-19 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerapp', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f401f5d-e3cb-4a8b-8b13-c1a7bd443e07'), primary_key=True, serialize=False),
        ),
    ]
