# Generated by Django 5.2.6 on 2025-12-19 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerapp', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
